name: Portsly
options:
  bundleIdPrefix: com.portsly
  deploymentTarget:
    macOS: '12.0'
  derivedDataPath: build
targets:
  Portsly:
    type: application
    platform: macOS
    sources:
      - Sources
      - Resources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.brightbase.portsly
        PRODUCT_NAME: Portsly
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_KEY_CFBundleDisplayName: Portsly
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHighResolutionCapable: YES
        SWIFT_VERSION: 5.9
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: Resources/Portsly.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "3GYP4YJ3DH"
